### ISSUE TITLE
Submit your week1 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project-2018/deliverables#1]
Submit your week 1 report here by publishing the link to your public GDrive slides.

Deadline Sunday 07th October 2018, 20:00h

**Comment by AndreuRodriguez** [comment]
T1-W1 - Traffic Sign Detection Google Slides. Authors: David Cara, Daniel Fuentes and Andreu Rodríguez. Click the following [link](https://docs.google.com/presentation/d/1aPvcD0OAAeWXg6jGYGzv0xeLoyCTgaydjQlMhUK2rHY/edit#slide=id.g43de223c6f_0_945) to access.

**Comment by albamhp** [comment]
T2-W1 - Traffic Sign Detection Google Slides. Authors: Alba Herrera, Jorge López, Claudia Baca and Quim Comas. Click the following [link](https://drive.google.com/file/d/1dLx_euxs3Vz-f7veDfhMevQPrb1hPzfU/view?usp=sharing) to access.

**Comment by nilaisr** [comment]
T8-W1 - Traffic Sign Detection Google Slides. Authors: Daniel Azemar, Nilai Sallent and Richard Segovia. Click the following [link](https://docs.google.com/presentation/d/1P-sS--nS_hfgjBwubaGhe280fWiep6P-Gf9fzmTL_q8/edit#slide=id.p6) to access.

**Comment by oscmansan** [comment]
T6-W1: https://docs.google.com/presentation/d/1nBRtiXVG-Y8eXCipx0A6d0QaGzMfS457llgKKzvm4pE/edit?usp=sharing

**Comment by mpQuintana** [comment]
T7 - W1 https://docs.google.com/presentation/d/1ePKRr5KmoWt76ahPIsWlCMuuLHRQs8TiQqqXMp17ibk/edit?usp=sharing

**Comment by sracela** [comment]
T4-W1 - Traffic Sign Detection Google Slides. Authors: Sara Cela, Manuel Rey, Zuzanna Szafranowska, Grzegorz Skorupko. Click the following [link](https://docs.google.com/presentation/d/1zt4D5yo7iwqHDx3IWhooRGGq5sHjh24lp3pR-FcG4vI/edit#slide=id.g43ae20836c_5_54)to access.

**Comment by pablorodriper** [comment]
T5-W1 - Authors:  Facundo Ferrín, Eric Marín, Agustina Pose, Pablo Rodríguez

[link](https://docs.google.com/presentation/d/1b-ZlQLzM9TtAoRaB38ctCQL5pCCEyb7k0PIQA2O4-Ik/edit?usp=sharing) to access.

**Comment by LauraMoraB** [comment]
T3-W1 - Traffic Sign Detection Google Slides. Authors: Gabriela Cordova, Laura Mora, Marc Nuñez y Aitor Sanchez. Click the following [Link](https://docs.google.com/presentation/d/1wR4Py7_Nnm0WoaqCjVEpyxrZK_LBKiUhbjyztCf6eio/edit?usp=sharing) to access
