### ISSUE TITLE
Reports week 2

### ISSUE THREAD

**Issue by marcnunez** [mcv-m1-project-2018/deliverables#2]

**Comment by marcnunez** [comment]
T3-W2 [Slides](https://docs.google.com/presentation/d/1BFFcjd7E4UqQ1QtxW26WLsQCHXzRjQ5NES8kIxdih-E/edit?usp=sharing)

**Comment by nokutu** [comment]
T2-W2 - Traffic Sign Detection Google Slides. Authors: Alba Herrera, Jorge López, Claudia Baca and Quim Comas. Click the following [link ](https://docs.google.com/presentation/d/1kx06u-0gJFBv7KE1-B77PAZxBDg5NpEtTMbMib1sHlw/edit?usp=sharing) to access.

**Comment by sracela** [comment]
T4-W2 Traffic Sign Detection Google Slides. Authors:
Sara Cela Alfonso
Manuel Rey Area
Grzegorz Skorupko
Zuzanna Szafranowska
Click the following [link](https://docs.google.com/presentation/d/1M5iAvDmA7IKI4wgyul57JVPrdAFecPO3bGmIBTD4Jbc/edit#slide=id.g35f391192_00) to access.

**Comment by mgilar** [comment]
T6-W2 - Traffic Sign Detection Google Slides. Authors: Gemma Canet, Daniel Fuentes, María Gil and Oscar Mañas. Click the following [link](https://docs.google.com/presentation/d/1PSFdh506pFM-w1FoEAQIxlq0nc_JtxRbhpyyStRbzZs/edit?usp=sharing) to access.

**Comment by sgbordils** [comment]
T7-W2 - https://docs.google.com/presentation/d/1KPf6XI2PzBsBNqqqFsbRrpup-y7diFhDlwhvaR9_1fI/edit?usp=sharing

**Comment by apose** [comment]
T5 - Week 2 - https://docs.google.com/presentation/d/1Oy81rFgygad0txVXnx7-GLGBpWKZUYybyXx_z-ZfJ_M/edit?usp=sharing

**Comment by richardseba** [comment]
T8-W2 - Traffic Sign Detection Google Slides. Authors: Daniel Azemar, Nilai Sallent, Richard Segovia and Andreu Rodríguez. Click the following [link ](https://docs.google.com/presentation/d/19BmV9G6NDPZks7Zq85y7btnq2WH7NqmhZFnjUr81j5A/edit?usp=sharing) to access.
