### ISSUE TITLE
Submit your week3 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project-2018/deliverables#3]
Submit your week 3 report here by publishing the link to your public GDrive slides.

Deadline Sunday 28th October 2018, 20:00h

**Comment by EricMKIV** [comment]
T5 -W3 Slides: [https://docs.google.com/presentation/d/1XbRKM1kPflb__5f7qZQpYcCGfWkNBzB-oF0166YiOcg/edit?usp=sharing](url)

**Comment by marcnunez** [comment]
T3-W3 [SLIDES](https://docs.google.com/presentation/d/1j5wq43_x7C8E13yXp9z-_NbkGvIINo_hGr-krjoKUpQ/edit?usp=sharing)

**Comment by AndreuRodriguez** [comment]
T8-W3 Painting Retrieval. Authors: Azemar, Daniel; Segovia, Richard; Sallent, Nilai; Rodríguez, Andreu. Link [here](https://docs.google.com/presentation/d/18nXz1vlMC2zR5DKWamQm43msEauqNZOKhynK0g5i6Po/edit#slide=id.g442c88b2ee_0_83)

**Comment by manurare** [comment]
T4-W3 [LINK](https://docs.google.com/presentation/d/1qf7twIpWXm59GeV41COrdZG8IAdU7Ic_xOqrIgs6M6Q/edit#slide=id.g35f391192_00)

**Comment by mgilar** [comment]
T6-W3 https://docs.google.com/presentation/d/1-h4P385VRnHgnV_NjKGB73K1nkfAbwQ27IFjV6ztuHY/edit?usp=sharing

**Comment by albamhp** [comment]
T2-W3 [Content Based Image Retrieval](https://docs.google.com/presentation/d/1Q0mnkQffr-dKm2s9suQMiGa8owuRh48ZLYF3pqtLeOI/edit?usp=sharing). Authors: Alba M Herrera, Claudia Baca, Jorge López, Quim Comas.

**Comment by mpQuintana** [comment]
T7-W3: https://docs.google.com/presentation/d/1Ve6RXHWRM_4FmjQa-RW1o_Xfz-Bayvkdj7pcpbXwDX0/edit?usp=sharing

**Comment by pablorodriper** [comment]
Team 5 - https://docs.google.com/presentation/d/1XbRKM1kPflb__5f7qZQpYcCGfWkNBzB-oF0166YiOcg/edit?usp=sharing
