### ISSUE TITLE
Submit your week4 report here

### ISSUE THREAD

**Issue by hamddan4** [mcv-m1-project-2018/deliverables#4]
Submit your week 4 report here by publishing the link to your public GDrive slides.

Deadline Sunday 4th November 2018, 20:00h

**Comment by hamddan4** [comment]
T8-W4: https://docs.google.com/presentation/d/1Z8YDa7hqxM5tfDe0XrATmd1pKbG9wJa_ugznJdgZoDo

**Comment by pablorodriper** [comment]
T5-W4 [link](https://docs.google.com/presentation/d/1tWVd662R5ZEbHGKEion_qD5LrbddEmTsDZsFVVCirNU/edit?usp=sharing)

**Comment by mgilar** [comment]
T6-W4 https://docs.google.com/presentation/d/1D61a-bVjyZCf4BbVQl9YfcG5YqrU2BCEWiNNLgGlvj4/edit?usp=sharing

**Comment by marcnunez** [comment]
T3-W4 [Slides](https://docs.google.com/presentation/d/1gwvwJHweARbpciVQil6GOjwD8iVNQvHEoLtzXYnCLP0/edit?usp=sharing)

**Comment by sgbordils** [comment]
T7-W4 https://docs.google.com/presentation/d/19CNVoQGSrd-nplA0uum8E3w0Hwkc6qx5wLt_Muy1D7M/edit?usp=sharing

**Comment by nokutu** [comment]
T2-W4 [https://docs.google.com/presentation/d/1NuoPnRLGN18iMK8679PJycPRDLwmzoREAQmSoDOSAKQ/edit?usp=sharing](https://docs.google.com/presentation/d/1NuoPnRLGN18iMK8679PJycPRDLwmzoREAQmSoDOSAKQ/edit?usp=sharing)

**Comment by sracela** [comment]
T4-W4 https://docs.google.com/presentation/d/18U0qSu4SL0Z-6Vy0tiLOItfes-LB8pkpYEGS3y0xjeU/edit#slide=id.g466cfe0566_1_236
