### ISSUE TITLE
Submit your week5 slides here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project-2018/deliverables#5]
Submit your week 5 report here by publishing the link to your public GDrive slides.

Deadline Sunday 18th November 2018, 20:00h

**Comment by richardseba** [comment]
T8-W5 https://docs.google.com/presentation/d/1GAVahjq5P8YqiqEeBlvcBl2R6SlNDQjd5h5xZvLzFNY/edit?usp=sharing

**Comment by mgilar** [comment]
T6-W5 https://docs.google.com/presentation/d/1RYVnIFVrv3Ad7gXQXL-TUAZGlIiReAokB57N6-Xb9u0/edit?usp=sharing

**Comment by nokutu** [comment]
T2-W5 [https://docs.google.com/presentation/d/1xpkQmHsIqs3AKZ8SBx-7rOjM1F7K-Ky6NhCgTS05iwA/edit?usp=sharing](https://docs.google.com/presentation/d/1xpkQmHsIqs3AKZ8SBx-7rOjM1F7K-Ky6NhCgTS05iwA/edit?usp=sharing)

**Comment by sracela** [comment]
T4-W5 https://docs.google.com/presentation/d/18sM-mAdhpcQFS5m5ExZSBFt41wQPWaJBWdBdbCST3l0/edit#slide=id.g35f391192_00

**Comment by EricMKIV** [comment]
T5-W5 https://docs.google.com/presentation/d/12F4uFUTdEs3EKYPeA8C9WYXeXYzLt5s2V7i4coVzj_E/edit?usp=sharing

**Comment by sgbordils** [comment]
T7-W5 https://docs.google.com/presentation/d/1VVVQ6x6dA3iZ01Q1ZDW5j_-Jp5Y1vnYxMLi4P2QiFpA/edit?usp=sharing

**Comment by marcnunez** [comment]
T3-W3 [Slides](https://docs.google.com/presentation/d/1MPyHJ0O-0h3pfrZpWe5Szsgoa5YH5YOaqLyUEx88rHY/edit?usp=sharing)
